# Generated by Django 6.0.4 on 2026-06-03 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
